# Generated by Django 2.2.13 on 2020-07-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiviert')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('button_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Button-Text')),
                ('button_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Button-Link')),
            ],
        ),
    ]
