# Generated by Django 2.2.13 on 2020-07-02 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('banners', '0003_auto_20200702_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='except_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Überall nur nicht auf dieser Seite'),
        ),
        migrations.AddField(
            model_name='banner',
            name='only_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Nur auf dieser Seite'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='color',
            field=models.CharField(choices=[('white', 'Weiß'), ('green', 'Grün'), ('blue', 'Blau'), ('red', 'Rot'), ('purple', 'Lila'), ('black', 'Schwarz')], default='white', max_length=16, verbose_name='Farbe'),
        ),
    ]
