# Generated by Django 2.2.13 on 2020-07-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_auto_20200702_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='except_page',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='only_page',
        ),
        migrations.AddField(
            model_name='banner',
            name='where',
            field=models.CharField(choices=[('everywhere', 'Alle Seiten'), ('homepage', 'Startseite')], default='everywhere', help_text='Auf welchen Seiten soll das Banner angezeigt werden?', max_length=100, verbose_name='Wo'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='color',
            field=models.CharField(choices=[('white', 'Weiß'), ('green', 'Grün'), ('blue', 'Blau'), ('red', 'Rot'), ('purple', 'Lila'), ('black', 'Schwarz')], default='white', help_text='Hintergrundfarbe', max_length=16, verbose_name='Farbe'),
        ),
    ]
