# Generated by Django 2.2.13 on 2020-07-02 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('banners', '0005_auto_20200702_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Kleines Bild, das links angezeigt wird.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='color',
            field=models.CharField(choices=[('white', 'Weiß'), ('green', 'Grün'), ('blue', 'Blau'), ('red', 'Rot'), ('purple', 'Lila'), ('black', 'Schwarz')], default='white', help_text='Hintergrundfarbe des Banners', max_length=16, verbose_name='Farbe'),
        ),
    ]
