# Generated by Django 2.2.13 on 2020-07-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_auto_20200702_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Kleines Bild, das links angezeigt wird.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Bild'),
        ),
    ]
