# Generated by Django 2.2.13 on 2020-07-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_auto_20200702_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Kleines Bild, das links angezeigt wird. Am besten Icons o.ä.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='where',
            field=models.CharField(choices=[('everywhere', 'Alle Seiten'), ('homepage', 'Nur Startseite'), ('not_homepage', 'Alle außer Startseite')], default='everywhere', help_text='Auf welchen Seiten soll das Banner angezeigt werden?', max_length=100, verbose_name='Wo'),
        ),
    ]
