# Generated by Django 2.2.13 on 2020-07-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_auto_20200702_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, help_text='Wird auf mobil nicht angezeigt', max_length=255, null=True, verbose_name='Button-Text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Kleines Bild, das links angezeigt werden kann. Icons o.ä.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Bild'),
        ),
    ]
