# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20161001_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='organizer',
            field=models.CharField(blank=True, help_text='externer Veranstalter, falls externe Veranstaltung', max_length=255, null=True, verbose_name='Veranstalter'),
        ),
    ]
