# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventpage_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='related_group',
            field=models.ForeignKey(blank=True, help_text='JANUN-Gruppe, falls Veranstaltung vom JANUN-Netzwerk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_pages', to='core.Group', verbose_name='JANUN-Gruppe'),
        ),
    ]
