# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20170118_2353'),
        ('events', '0016_eventpage_hyphenated_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarFormPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BasePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basepage',),
        ),
    ]
