# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('events', '0018_seminarformpage_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminarformpage',
            options={'verbose_name': 'Formular'},
        ),
        migrations.AddField(
            model_name='seminarformpage',
            name='richtlinie',
            field=models.ForeignKey(blank=True, help_text='Wird im Formular verlinkt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Seminarabrechnungsrichtlinie'),
        ),
    ]
