# Generated by Django 2.2.8 on 2019-12-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20191214_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='color',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='late_attendence',
        ),
    ]
