# Generated by Django 2.2.9 on 2019-12-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20191216_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='location_address',
            field=models.CharField(blank=True, help_text='Straße, Hausnummer etc.', max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='location_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='location_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='location_postcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postleitzahl'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='location',
            field=models.CharField(blank=True, help_text='Altes Ortsfeld', max_length=255, null=True, verbose_name='Ort'),
        ),
    ]
