# Generated by Django 2.2.9 on 2019-12-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20191226_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='location_name',
            field=models.CharField(blank=True, help_text='Name des Veranstaltungsortes', max_length=255, null=True, verbose_name='Name'),
        ),
    ]
