# Generated by Django 2.2.9 on 2019-12-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20191226_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='location_address',
            field=models.TextField(blank=True, help_text='Straße, Hausnummer etc.', null=True, verbose_name='Adresse'),
        ),
    ]
