# Generated by Django 2.2.9 on 2019-12-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20191226_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventindexpage',
            name='header_image',
        ),
        migrations.AlterField(
            model_name='eventindexpage',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Überschrift'),
        ),
    ]
