# Generated by Django 2.2.10 on 2020-03-26 16:29

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20200116_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Veranstaltungsart',
                'verbose_name_plural': 'Veranstaltungsarten',
            },
        ),
        migrations.AddField(
            model_name='eventpage',
            name='event_type',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='seminars', to='events.EventType', verbose_name='Art der Veranstaltung'),
        ),
    ]
