# Generated by Django 2.2.17 on 2021-02-05 01:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_group_instagram_url'),
        ('events', '0038_auto_20201228_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='organizer',
            field=models.CharField(blank=True, help_text='Name des externen Veranstalters, falls externe Veranstaltung', max_length=255, null=True, verbose_name='Veranstalter'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='related_group',
            field=models.ForeignKey(blank=True, help_text='(alt)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Group', verbose_name='JANUN-Gruppe'),
        ),
        migrations.CreateModel(
            name='EventPageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventpage', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_groups', to='events.EventPage')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pages', to='core.Group')),
            ],
            options={
                'unique_together': {('eventpage', 'group')},
            },
        ),
    ]
