# Generated by Django 2.2.19 on 2021-03-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_copy_event_related_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindexpage',
            name='show_all_sites',
            field=models.BooleanField(default=False, help_text='Sollen die Veranstaltungen aller Websites auf diesem Server angezeigt werden oder nur, die die Kinder von dieser Seite sind?', verbose_name='Alle Seiten anzeigen'),
        ),
    ]
