# Generated by Django 2.2.13 on 2020-06-13 21:04

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobofferpage',
            name='valid_through',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now, message='Sollte in der Zukunft liegen')], verbose_name='Bewerbungsfrist'),
        ),
    ]
