# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 20:21
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('wagtailimages', '0010_change_on_delete_behaviour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subheading', models.CharField(blank=True, max_length=255, null=True, verbose_name='optionale Unterüberschrift')),
                ('body', wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', core.models.ImageBlock())), blank=True, help_text='Inhalt des Artikels')),
                ('highlight', models.BooleanField(default=False, help_text='Ist dies ein ge-highlighteter Artikel? Falls ja, taucht es z.B. auf der Startseite auf.', verbose_name='Highlight')),
                ('dont_crop', models.BooleanField(default=False, help_text='Normalerweise wird das Hauptbild beschnitten, um besser auf die Seite zu passen. Falls ja, wird das Seitenverhältnis des Hauptbildes beibehalten.', verbose_name='Hauptbild nicht abschneiden')),
                ('main_image', models.ForeignKey(blank=True, help_text='Bild, das den Artikel repräsentiert. Wird in Übersichten verwendet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Hauptbild')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Current',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Aktuelles',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Startseite',
            },
            bases=('wagtailcore.page',),
        ),
    ]
