# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedimage',
            name='original_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Original Title'),
        ),
    ]
