# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160415_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Logo'),
        ),
    ]
