# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 17:29
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160520_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='contact_mail',
            field=models.EmailField(blank=True, help_text='Die E-Mail-Adresse, um Kontakt für diese Veranstaltung aufzunehmen', max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='facebook_event_url',
            field=core.fields.FacebookEventURLField(blank=True, help_text='Die URL zum Facebook-Event dieser Veranstaltung', null=True, verbose_name='Facebook Event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='website_url',
            field=core.fields.PrettyURLField(blank=True, help_text='Die URL einer externen Website zu dieser Veranstaltung', null=True, verbose_name='externe Website'),
        ),
    ]
