# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160524_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='ganztägig'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='late_attendence',
            field=models.BooleanField(default=False, help_text='Falls dies ein mehrtägiger Termin ist: Ist es auch möglich z.B. erst am zweiten Tag zu kommen?', verbose_name='späte Teilnahme möglich'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Bild für diese Veranstaltung. Bitte kein Gruppen- oder JANUN-Logo!', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Bild'),
        ),
    ]
