# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 10:36
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160607_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='external_event',
            field=models.BooleanField(default=False, verbose_name='externe Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='ganztägig'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='color',
            field=models.CharField(blank=True, choices=[('rgb(70, 187, 0)', 'Grün'), ('rgb(196, 23, 55)', 'Rot'), ('rgb(0, 118, 164)', 'Blau'), ('rgb(233, 88, 34)', 'Orange')], help_text='Die Veranstaltung bekommt diese Farbe, falls es kein Bild gibt.', max_length=18, null=True, verbose_name='Farbe als Ersatz für Bild'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='contact_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='facebook_event_url',
            field=core.fields.FacebookEventURLField(blank=True, null=True, verbose_name='Facebook-Event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='late_attendence',
            field=models.BooleanField(default=False, help_text='Ist es auch möglich z.B. erst am zweiten Tag zu kommen?', verbose_name='späte Teilnahme möglich'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Bitte kein Gruppen- oder JANUN-Logo!', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='register_url',
            field=core.fields.PrettyURLField(blank=True, help_text='z.B. auf der externen Seite oder bei einem Formularservice', null=True, verbose_name='Link zu Anmelde-Formular'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='related_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_pages', to='core.Group', verbose_name='Zugehörige JANUN-Gruppe'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='website_url',
            field=core.fields.PrettyURLField(blank=True, help_text='z.B. auf der Veranstalter-Homepage', null=True, verbose_name='externe Website'),
        ),
    ]
