# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20160623_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='external_event',
        ),
    ]
