# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 13:06
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='title',
        ),
        migrations.AddField(
            model_name='highlight',
            name='title_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='end_datetime',
            field=models.DateTimeField(blank=True, default=core.models.get_in_14_days, null=True, verbose_name='Endzeit'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Startzeit'),
        ),
    ]
