# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20160830_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='title_color',
            field=models.CharField(blank=True, choices=[('brown', 'Braun'), ('green', 'Grün'), ('red', 'Rot'), ('blue', 'Blau'), ('orange', 'Orange')], default='brown', max_length=255, null=True, verbose_name='Titelfarbe'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='core.Person', verbose_name='Autor_in'),
        ),
    ]
