# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20160913_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
