# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_standardpage_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleindexpage',
            options={'verbose_name': 'Sammlung von Artikeln'},
        ),
    ]
