# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20161001_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage'),
        ),
        migrations.AlterField(
            model_name='attributedimage',
            name='attribution',
            field=models.CharField(blank=True, max_length=255, verbose_name='Quellenangabe'),
        ),
    ]
