# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20161014_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='header_image',
        ),
    ]
