# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_homepage_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedrendition',
            name='filter_spec',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='attributedrendition',
            name='filter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
