# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:58
from __future__ import unicode_literals

from django.db import migrations

from wagtail.images.utils import get_fill_filter_spec_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20161028_1457'),
    ]

    # get_fill_filter_spec_migrations errors out
    # https://github.com/wagtail/wagtail/issues/5067
    # forward, reverse = get_fill_filter_spec_migrations('core', 'AttributedRendition')
    # operations = [
    #     migrations.RunPython(forward, reverse),
    # ]
