# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 17:22
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20161107_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='contact_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='group',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='group',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Telefonnummer'),
        ),
        migrations.AddField(
            model_name='group',
            name='facebook_url',
            field=core.fields.FacebookProfileURLField(blank=True, null=True, verbose_name='Facebook-Profil'),
        ),
        migrations.AddField(
            model_name='group',
            name='website',
            field=core.fields.PrettyURLField(blank=True, null=True, verbose_name='externe Website'),
        ),
    ]
