# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20161115_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributedimage',
            name='attribution',
            field=models.CharField(default='JANUN e.V.', max_length=255, verbose_name='Quellenangabe'),
        ),
    ]
