# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20161201_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Group')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.group',),
        ),
    ]
