# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_attributedimage_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributedimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
