# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_standardpage_feed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributedrendition',
            name='filter_spec',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attributedrendition',
            name='focal_point_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=16),
        ),
        # migrations.RemoveField(
        #     model_name='attributedrendition',
        #     name='filter',
        # ),
        migrations.AlterUniqueTogether(
            name='attributedrendition',
            unique_together=set([('image', 'filter_spec', 'focal_point_key')]),
        ),
    ]
