# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20170720_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formpage',
            options={'verbose_name': 'Formular', 'verbose_name_plural': 'Formulare'},
        ),
        migrations.AddField(
            model_name='formpage',
            name='confirmation_mail_field',
            field=models.CharField(blank=True, help_text='Benutzer bekommt Bestägigungsmail an Adresse aus diesem Feld.', max_length=255, verbose_name='Bestätigungsmail-Feld'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='confirmation_mail_text',
            field=models.TextField(blank=True, verbose_name='Text der Bestätigungsmail'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Wird über dem Formular angezeigt.', verbose_name='Einführung'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='thank_you_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Wird angezeigt, nachdem das Formular erfolgreich abgesendet wurde.', verbose_name='Danke-Text'),
        ),
    ]
