# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 15:15
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20170727_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField((('header', wagtail.core.blocks.StructBlock((('background', wagtail.images.blocks.ImageChooserBlock(label='Hintergrundbild', required=False)),))), ('button', wagtail.core.blocks.StructBlock((('text', wagtail.core.blocks.CharBlock(label='Text')), ('link', wagtail.core.blocks.URLBlock(label='Link')), ('color', wagtail.core.blocks.ChoiceBlock(choices=[('green', 'Grün'), ('red', 'Rot'), ('blue', 'Blau'), ('orange', 'Orange')], label='Farbe')))))), blank=True, verbose_name='Inhalt'),
        ),
    ]
