# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:55
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20170728_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField((('header', wagtail.core.blocks.StructBlock((('background', wagtail.images.blocks.ImageChooserBlock(label='Hintergrundbild', required=False)),))), ('paragraph2', wagtail.core.blocks.StructBlock((('big', wagtail.core.blocks.BooleanBlock(default=False, label='Groß')), ('center', wagtail.core.blocks.BooleanBlock(default=False, label='zentriert')), ('text', wagtail.core.blocks.RichTextBlock())))), ('button', wagtail.core.blocks.StructBlock((('text', wagtail.core.blocks.CharBlock(label='Text')), ('link', wagtail.core.blocks.URLBlock(label='Link')), ('color', wagtail.core.blocks.ChoiceBlock(choices=[('green', 'Grün'), ('red', 'Rot'), ('blue', 'Blau'), ('orange', 'Orange')], label='Farbe'))))), ('teaser', wagtail.core.blocks.StructBlock((('background', wagtail.images.blocks.ImageChooserBlock(label='Hintergrundbild', required=False)), ('title', wagtail.core.blocks.CharBlock(label='Titel', required=False)), ('subtitle', wagtail.core.blocks.CharBlock(label='Untertitel', required=False))))), ('highlights', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(label='Überschrift', required=False)), ('objects', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock()))))), ('newsletter', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(label='Überschrift', required=False)), ('text', wagtail.core.blocks.RichTextBlock(label='Text', required=False)), ('example_url', wagtail.core.blocks.URLBlock(label='Link zu Beispiel-E-Mail', required=False)))))), blank=True, verbose_name='Inhalt'),
        ),
    ]
