# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20170923_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='list_on_group_index_page',
            field=models.BooleanField(default='True', verbose_name='Auf Netzwerk & Projekte auflisten?'),
        ),
    ]
