# Generated by Django 2.2.8 on 2019-12-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20191214_0338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Highlight',
        ),
    ]
