# Generated by Django 2.2.12 on 2020-04-07 15:34

from django.db import migrations, models, connection
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


def author_id_exists():
    """checks if author_id already exists"""
    try:
        cursor = connection.cursor()
        if not cursor:
            raise Exception
        table = connection.introspection.get_table_description(cursor, "core_article")
    except:
        raise Exception("unable to determine if the table exists")
    return "author_id" in [info.name for info in table]


def add_article_author(apps, schema_editor):
    """Add author_id only if non-existent"""
    if not author_id_exists():
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pages",
                to="contact.PersonPage",
                verbose_name="Autor_in",
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0021_auto_20200405_1652"),
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("core", "0083_auto_20200405_1652"),
    ]

    operations = [
        migrations.RunPython(add_article_author),
        # migrations.AddField(
        #     model_name='article',
        #     name='author',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='contact.PersonPage', verbose_name='Autor_in'),
        # ),
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "header",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Hintergrundbild", required=False
                                    ),
                                ),
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        label="Überschrift", required=False
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        label="Text", required=False
                                    ),
                                ),
                                (
                                    "buttons",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "text",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="Text"
                                                    ),
                                                ),
                                                (
                                                    "link",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="Link"
                                                    ),
                                                ),
                                                (
                                                    "primary",
                                                    wagtail.core.blocks.BooleanBlock(
                                                        label="Primär", required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "paragraph2",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "big",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="Groß", required=False
                                    ),
                                ),
                                (
                                    "center",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="zentriert", required=False
                                    ),
                                ),
                                ("text", wagtail.core.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "button",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("text", wagtail.core.blocks.CharBlock(label="Text")),
                                (
                                    "link",
                                    wagtail.core.blocks.URLBlock(
                                        label="Link", required=False
                                    ),
                                ),
                                (
                                    "mail",
                                    wagtail.core.blocks.EmailBlock(
                                        help_text="wird anstelle von link benutzt",
                                        label="E-Mail",
                                        required=False,
                                    ),
                                ),
                                (
                                    "color",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("green", "Grün"),
                                            ("red", "Rot"),
                                            ("blue", "Blau"),
                                            ("orange", "Orange"),
                                            ("purple", "Lila"),
                                        ],
                                        label="Farbe",
                                    ),
                                ),
                                (
                                    "aslink",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="ohne Hintergrund", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "teaser",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Hintergrundbild", required=False
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.core.blocks.CharBlock(
                                        label="Titel", required=False
                                    ),
                                ),
                                (
                                    "subtitle",
                                    wagtail.core.blocks.CharBlock(
                                        label="Untertitel", required=False
                                    ),
                                ),
                                (
                                    "rotate",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="gedreht", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "highlights",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        label="Überschrift", required=False
                                    ),
                                ),
                                (
                                    "objects",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.PageChooserBlock(),
                                        label="Objekte",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "newsletter",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        label="Überschrift", required=False
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        label="Text", required=False
                                    ),
                                ),
                                (
                                    "example_url",
                                    wagtail.core.blocks.URLBlock(
                                        label="Link zu Beispiel-E-Mail", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "box",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        label="Überschrift", required=False
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        label="Text", required=False
                                    ),
                                ),
                                (
                                    "buttons",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "text",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="Text"
                                                    ),
                                                ),
                                                (
                                                    "link",
                                                    wagtail.core.blocks.URLBlock(
                                                        label="Link", required=False
                                                    ),
                                                ),
                                                (
                                                    "mail",
                                                    wagtail.core.blocks.EmailBlock(
                                                        help_text="wird anstelle von link benutzt",
                                                        label="E-Mail",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "color",
                                                    wagtail.core.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("green", "Grün"),
                                                            ("red", "Rot"),
                                                            ("blue", "Blau"),
                                                            ("orange", "Orange"),
                                                            ("purple", "Lila"),
                                                        ],
                                                        label="Farbe",
                                                    ),
                                                ),
                                                (
                                                    "aslink",
                                                    wagtail.core.blocks.BooleanBlock(
                                                        label="ohne Hintergrund",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "gap",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "size",
                                    wagtail.core.blocks.DecimalBlock(
                                        help_text="Größe des vertikalen Abstands in Pixeln",
                                        label="Größe",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "events",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        label="Überschrift", required=False
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "embed",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "embed",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="von z.B. einem Youtube-Video, Facebook-Post, Instagram-Bild, …",
                                        label="URL",
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        label="opt. Beschrift.", required=False
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("text-width", "Text-Breite"),
                                            ("over-text-width", "Über-Text-Breite"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "iframe",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="URL zu der Website, die mittels Iframe eingebunden werden soll.",
                                        label="URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "allowFullScreen",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="Vollbild erlauben?", required=False
                                    ),
                                ),
                                (
                                    "height",
                                    wagtail.core.blocks.DecimalBlock(
                                        default="1000", help_text="in px", label="Höhe"
                                    ),
                                ),
                                (
                                    "width",
                                    wagtail.core.blocks.DecimalBlock(
                                        default="1000",
                                        help_text="in px",
                                        label="Breite",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video_link",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="URL zu dem Video, auf das verlinkt wird",
                                        label="URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Bild (schwarz wenn nichts angegeben)",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        label="Bild-Unterschrift", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                verbose_name="Inhalt",
            ),
        ),
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soziale Medien",
                "verbose_name_plural": "Soziale Medien",
            },
        ),
        migrations.CreateModel(
            name="SocialMediaEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                (
                    "icon_color",
                    models.ImageField(upload_to="", verbose_name="buntes Icon"),
                ),
                (
                    "icon_gray",
                    models.ImageField(upload_to="", verbose_name="graues Icon"),
                ),
                ("tooltip", models.CharField(blank=True, max_length=255)),
                (
                    "settings",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.SocialMediaSettings",
                    ),
                ),
            ],
        ),
    ]
