# Generated by Django 2.2.12 on 2020-04-07 15:49

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20200407_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettingssocialmediaentry',
            name='page',
        ),
        migrations.AddField(
            model_name='socialmediasettingssocialmediaentry',
            name='setting',
            field=modelcluster.fields.ParentalKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='core.SocialMediaSettings'),
            preserve_default=False,
        ),
    ]
