# Generated by Django 2.2.12 on 2020-04-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20200407_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettingssocialmediaentry',
            name='icon_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Buntes Icon'),
        ),
        migrations.AlterField(
            model_name='socialmediasettingssocialmediaentry',
            name='icon_gray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Graues Icon'),
        ),
    ]
