# Generated by Django 2.2.12 on 2020-05-19 09:26

import core.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        # ("contact", "0022_auto_20200519_1126"),
        ("core", "0088_auto_20200409_1859"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Projekt", "verbose_name_plural": "Projekte"},
        ),
        migrations.RemoveField(model_name="groupindexpage", name="header_image",),
        migrations.AddField(
            model_name="groupindexpage",
            name="highlight_in_heading",
            field=models.CharField(
                blank=True,
                help_text="Wiederhole Text aus der Überschrift der farblich hervorgehoben werden soll",
                max_length=255,
                verbose_name="Hervorhebungen in der Überschrift",
            ),
        ),
        migrations.AddField(
            model_name="groupindexpage",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Untertitel"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "paragraph",
                        core.blocks.ParagraphBlock(
                            features=[
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "document-link",
                                "anchor-identifier",
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Bild"
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        label="Bildunterschrift", required=False
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("text-width", "Text-Breite"),
                                            ("over-text-width", "Über-Text-Breite"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "several_images",
                        core.blocks.ImagesBlock(core.blocks.ImageCarouselBlock),
                    ),
                    (
                        "gallery",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "collection",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=core.blocks.get_image_gallery_choices,
                                        help_text="Die Bilder aus der Sammlung werden dann als Gallerie angezeigt.",
                                        label="Sammlung",
                                    ),
                                ),
                                (
                                    "start_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Das Bild, das als erstes angezeigt wird.",
                                        label="erstes Bild",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "embed",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "embed",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="von z.B. einem Youtube-Video, Facebook-Post, Instagram-Bild, …",
                                        label="URL",
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        label="opt. Beschrift.", required=False
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("text-width", "Text-Breite"),
                                            ("over-text-width", "Über-Text-Breite"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "button",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("text", wagtail.core.blocks.CharBlock(label="Text")),
                                (
                                    "link",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Schreibe https://example.com für einen externen Link, /unterseite für einen internen, #sektion für einen Anchor-Link, mailto:max@muster.de für eine E-Mail-Adresse, tel:+49123121 für eine Telefonnummer etc.",
                                        label="Link",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("attachment", core.blocks.Attachment()),
                    ("table", wagtail.contrib.table_block.blocks.TableBlock()),
                    (
                        "map_image",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "tile_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="URL zu den Kacheln, aus denen das Bild besteht. Benutze {z}, {x}, {y} in der URL für die Koordinaten",
                                        label="Kachel-URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "height",
                                    wagtail.core.blocks.DecimalBlock(
                                        help_text="in speziellen Leaflet Einheiten",
                                        label="Höhe",
                                        required=True,
                                    ),
                                ),
                                (
                                    "width",
                                    wagtail.core.blocks.DecimalBlock(
                                        help_text="in speziellen Leaflet Einheiten",
                                        label="Breite",
                                        required=True,
                                    ),
                                ),
                                (
                                    "attribution",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wird unten rechts im Bild angezeigt.",
                                        label="Urheber",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "iframe",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="URL zu der Website, die mittels Iframe eingebunden werden soll.",
                                        label="URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "allowFullScreen",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="Vollbild erlauben?", required=False
                                    ),
                                ),
                                (
                                    "height",
                                    wagtail.core.blocks.DecimalBlock(
                                        default="1000", help_text="in px", label="Höhe"
                                    ),
                                ),
                                (
                                    "width",
                                    wagtail.core.blocks.DecimalBlock(
                                        default="1000",
                                        help_text="in px",
                                        label="Breite",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video_link",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="URL zu dem Video, auf das verlinkt wird",
                                        label="URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Bild (schwarz wenn nichts angegeben)",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        label="Bild-Unterschrift", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                verbose_name="Inhalt",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "header",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Hintergrundbild", required=False
                                    ),
                                ),
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        label="Überschrift", required=False
                                    ),
                                ),
                                (
                                    "highlight_in_heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wiederhole Text aus der Überschrift der farblich hervorgehoben werden soll",
                                        label="Hervorhebungen in der Überschrift",
                                        required=False,
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        label="Text", required=False
                                    ),
                                ),
                                (
                                    "text_mobile",
                                    wagtail.core.blocks.RichTextBlock(
                                        label="Text (mobil)", required=False
                                    ),
                                ),
                                (
                                    "buttons",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "text",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="Text"
                                                    ),
                                                ),
                                                (
                                                    "link",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="Link"
                                                    ),
                                                ),
                                                (
                                                    "primary",
                                                    wagtail.core.blocks.BooleanBlock(
                                                        label="Primär", required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                                (
                                    "white_background",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="weißer Hintergrund", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "highlights",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        label="Überschrift", required=False
                                    ),
                                ),
                                (
                                    "objects",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.PageChooserBlock(),
                                        label="Objekte",
                                    ),
                                ),
                                (
                                    "white_background",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="weißer Hintergrund", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "signup",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        label="Überschrift", required=False
                                    ),
                                ),
                                (
                                    "highlight_in_heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wiederhole Text aus der Überschrift der farblich hervorgehoben werden soll",
                                        label="Hervorhebungen in der Überschrift",
                                        required=False,
                                    ),
                                ),
                                (
                                    "white_background",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="weißer Hintergrund", required=False
                                    ),
                                ),
                                (
                                    "background",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Hintergrund-Bild", required=False
                                    ),
                                ),
                                (
                                    "blocks",
                                    wagtail.core.blocks.StreamBlock(
                                        [
                                            (
                                                "link",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "heading",
                                                            wagtail.core.blocks.CharBlock(
                                                                label="Überschrift",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.core.blocks.RichTextBlock(
                                                                label="Text",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            wagtail.core.blocks.URLBlock(
                                                                label="Button-URL"
                                                            ),
                                                        ),
                                                        (
                                                            "button_text",
                                                            wagtail.core.blocks.CharBlock(
                                                                label="Button Text"
                                                            ),
                                                        ),
                                                        (
                                                            "button_color",
                                                            wagtail.core.blocks.CharBlock(
                                                                default="#3a9d00",
                                                                label="Button Farbe",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "button_icon",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                label="Icon",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "button_hint",
                                                            wagtail.core.blocks.CharBlock(
                                                                label="Button Hinweistext",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "homepage_image",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Bild"
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        label="Bildunterschrift", required=False
                                    ),
                                ),
                                (
                                    "white_background",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="weißer Hintergrund", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "groups",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        label="Überschrift", required=False
                                    ),
                                ),
                                (
                                    "highlight_in_heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wiederhole Text aus der Überschrift der farblich hervorgehoben werden soll",
                                        label="Hervorhebungen in der Überschrift",
                                        required=False,
                                    ),
                                ),
                                (
                                    "white_background",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="weißer Hintergrund", required=False
                                    ),
                                ),
                                (
                                    "background",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Hintergrund-Bild", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "cards",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        label="Überschrift", required=False
                                    ),
                                ),
                                (
                                    "highlight_in_heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wiederhole Text aus der Überschrift der farblich hervorgehoben werden soll",
                                        label="Hervorhebungen in der Überschrift",
                                        required=False,
                                    ),
                                ),
                                (
                                    "white_background",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="weißer Hintergrund", required=False
                                    ),
                                ),
                                (
                                    "cards",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "heading",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="Überschrift"
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        label="Bild"
                                                    ),
                                                ),
                                                (
                                                    "text",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="Text", required=False
                                                    ),
                                                ),
                                                (
                                                    "url",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="URL", required=False
                                                    ),
                                                ),
                                                (
                                                    "button_text",
                                                    wagtail.core.blocks.CharBlock(
                                                        label="Button-Text",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "fit_image",
                                                    wagtail.core.blocks.BooleanBlock(
                                                        default=True,
                                                        label="Bild an Rahmen anpassen",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "movie",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        label="Überschrift", required=False
                                    ),
                                ),
                                (
                                    "highlight_in_heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wiederhole Text aus der Überschrift der farblich hervorgehoben werden soll",
                                        label="Hervorhebungen in der Überschrift",
                                        required=False,
                                    ),
                                ),
                                (
                                    "white_background",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="weißer Hintergrund", required=False
                                    ),
                                ),
                                (
                                    "background",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Hintergrund-Bild", required=False
                                    ),
                                ),
                                (
                                    "url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="URL zu dem Video, auf das verlinkt wird",
                                        label="URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Bild (schwarz wenn nichts angegeben)",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        label="Bildunterschrift", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "statements",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        label="Überschrift", required=False
                                    ),
                                ),
                                (
                                    "highlight_in_heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wiederhole Text aus der Überschrift der farblich hervorgehoben werden soll",
                                        label="Hervorhebungen in der Überschrift",
                                        required=False,
                                    ),
                                ),
                                (
                                    "white_background",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="weißer Hintergrund", required=False
                                    ),
                                ),
                                (
                                    "statements",
                                    wagtail.core.blocks.ListBlock(
                                        core.blocks.StatementBlock
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                verbose_name="Inhalt",
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "paragraph",
                        core.blocks.ParagraphBlock(
                            features=[
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "document-link",
                                "anchor-identifier",
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Bild"
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        label="Bildunterschrift", required=False
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("text-width", "Text-Breite"),
                                            ("over-text-width", "Über-Text-Breite"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "several_images",
                        core.blocks.ImagesBlock(core.blocks.ImageCarouselBlock),
                    ),
                    (
                        "gallery",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "collection",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=core.blocks.get_image_gallery_choices,
                                        help_text="Die Bilder aus der Sammlung werden dann als Gallerie angezeigt.",
                                        label="Sammlung",
                                    ),
                                ),
                                (
                                    "start_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Das Bild, das als erstes angezeigt wird.",
                                        label="erstes Bild",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "embed",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "embed",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="von z.B. einem Youtube-Video, Facebook-Post, Instagram-Bild, …",
                                        label="URL",
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        label="opt. Beschrift.", required=False
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("text-width", "Text-Breite"),
                                            ("over-text-width", "Über-Text-Breite"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "button",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("text", wagtail.core.blocks.CharBlock(label="Text")),
                                (
                                    "link",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Schreibe https://example.com für einen externen Link, /unterseite für einen internen, #sektion für einen Anchor-Link, mailto:max@muster.de für eine E-Mail-Adresse, tel:+49123121 für eine Telefonnummer etc.",
                                        label="Link",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("attachment", core.blocks.Attachment()),
                    ("table", wagtail.contrib.table_block.blocks.TableBlock()),
                    (
                        "map_image",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "tile_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="URL zu den Kacheln, aus denen das Bild besteht. Benutze {z}, {x}, {y} in der URL für die Koordinaten",
                                        label="Kachel-URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "height",
                                    wagtail.core.blocks.DecimalBlock(
                                        help_text="in speziellen Leaflet Einheiten",
                                        label="Höhe",
                                        required=True,
                                    ),
                                ),
                                (
                                    "width",
                                    wagtail.core.blocks.DecimalBlock(
                                        help_text="in speziellen Leaflet Einheiten",
                                        label="Breite",
                                        required=True,
                                    ),
                                ),
                                (
                                    "attribution",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wird unten rechts im Bild angezeigt.",
                                        label="Urheber",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "iframe",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="URL zu der Website, die mittels Iframe eingebunden werden soll.",
                                        label="URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "allowFullScreen",
                                    wagtail.core.blocks.BooleanBlock(
                                        label="Vollbild erlauben?", required=False
                                    ),
                                ),
                                (
                                    "height",
                                    wagtail.core.blocks.DecimalBlock(
                                        default="1000", help_text="in px", label="Höhe"
                                    ),
                                ),
                                (
                                    "width",
                                    wagtail.core.blocks.DecimalBlock(
                                        default="1000",
                                        help_text="in px",
                                        label="Breite",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video_link",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="URL zu dem Video, auf das verlinkt wird",
                                        label="URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Bild (schwarz wenn nichts angegeben)",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        label="Bild-Unterschrift", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                verbose_name="Inhalt",
            ),
        ),
    ]
