# Generated by Django 2.2.12 on 2020-05-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_auto_20200519_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="basepage",
            name="megamenu_category",
            field=models.CharField(
                blank=True,
                help_text="Wird bei Untermenüs benutzt, um Unterseiten weiter zu gruppieren.",
                max_length=100,
                null=True,
                verbose_name="Kategorie in Menu",
            ),
        ),
    ]
