# Generated by Django 2.2.13 on 2020-06-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0022_auto_20200519_1126'),
        ("core", "0091_auto_20200605_2037"),
    ]

    operations = [
        ## contact.PersonPage does not exist anymore
        # migrations.AddField(
        #     model_name="article",
        #     name="author",
        #     field=models.ForeignKey(
        #         blank=True,
        #         null=True,
        #         on_delete=django.db.models.deletion.SET_NULL,
        #         related_name="pages",
        #         to="contact.PersonPage",
        #         verbose_name="Autor_in",
        #     ),
        # ),
    ]
