# Generated by Django 2.2.13 on 2020-07-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_article_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
