# Generated by Django 2.2.17 on 2021-02-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20201228_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram-Profil'),
        ),
    ]
