# Generated by Django 2.2.19 on 2021-03-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_group_instagram_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleGroupIndexPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BasePage')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='Überschrift')),
                ('highlight_in_heading', models.CharField(blank=True, help_text='Wiederhole Text aus der Überschrift der farblich hervorgehoben werden soll', max_length=255, verbose_name='Hervorhebungen in der Überschrift')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Untertitel')),
            ],
            options={
                'verbose_name': 'Auflistung von Gruppen (Lüneburg)',
            },
            bases=('core.basepage',),
        ),
    ]
