# Generated by Django 2.2.19 on 2021-03-18 13:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_simplegroupindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplegroupindexpage',
            name='coops',
            field=wagtail.core.fields.StreamField([('coop', wagtail.core.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(label='Logo')), ('title', wagtail.core.blocks.CharBlock(label='Untertitel', required=False)), ('url', wagtail.core.blocks.URLBlock(label='Link', required=False))]))], blank=True),
        ),
    ]
