# Generated by Django 2.2.19 on 2021-03-22 17:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_simplegroupindexpage_coops'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplegroupindexpage',
            name='coops_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Wird bei den Kooperationen angezeigt.', verbose_name='Kooperationen-Text'),
        ),
        migrations.AddField(
            model_name='simplegroupindexpage',
            name='groups_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Wird bei den Gruppen angezeigt.', verbose_name='Gruppen-Text'),
        ),
        migrations.AddField(
            model_name='simplegroupindexpage',
            name='projects_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Wird bei den Projekten angezeigt.', verbose_name='Projekte-Text'),
        ),
        migrations.AlterField(
            model_name='simplegroupindexpage',
            name='coops',
            field=wagtail.core.fields.StreamField([('coop', wagtail.core.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(label='Logo')), ('title', wagtail.core.blocks.CharBlock(label='Untertitel', required=False)), ('url', wagtail.core.blocks.URLBlock(label='Link', required=False))]))], blank=True, verbose_name='Kooperationen'),
        ),
    ]
