# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 13:15
from __future__ import unicode_literals

import current.models
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0011_remove_article_hide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', current.models.ImageBlock())), blank=True, help_text='Inhalt des Artikels'),
        ),
    ]
