# Generated by Django 2.2.14 on 2020-09-08 16:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_delete_banner'),
        ('staff', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafflisting',
            name='content',
        ),
        migrations.AddField(
            model_name='stafflisting',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Bild'),
        ),
        migrations.AddField(
            model_name='stafflisting',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Intro'),
        ),
    ]
