# Generated by Django 2.2.14 on 2020-09-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200908_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('ljb', 'Landesbüro Hannover'), ('lgb', 'Landesbüro Lüneburg'), ('brueter', 'Vorstand (Brüter)')], default='ljb', max_length=255, verbose_name='Abteilung'),
        ),
    ]
