# Generated by Django 2.2.14 on 2020-09-09 19:15

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflisting',
            name='outro',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Outro'),
        ),
    ]
