# Generated by Django 2.2.14 on 2020-09-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_stafflisting_outro'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kommentar zu Telefonnummer'),
        ),
    ]
