# Generated by Django 2.2.19 on 2021-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20201228_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('ljb', 'Landesbüro Hannover'), ('lgb', 'Landesbüro Lüneburg'), ('goe', 'Landesbüro Göttingen'), ('old', 'Landesbüro Oldenburg'), ('brueter', 'Vorstand (Brüter)')], default='ljb', max_length=255, verbose_name='Abteilung'),
        ),
    ]
