# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 18:41
from __future__ import unicode_literals

import core.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20160908_1602'),
        ('contact', '0002_auto_20160907_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactIndex',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BasePage')),
            ],
            options={
                'verbose_name': 'Auflistung von Kontakten',
            },
            bases=('core.basepage',),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='text',
            field=wagtail.core.fields.StreamField((('h2', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(label='Titel')), ('color', wagtail.core.blocks.ChoiceBlock(choices=[('brown', 'Braun'), ('green', 'Grün'), ('red', 'Rot'), ('blue', 'Blau'), ('orange', 'Orange')], default='brown', label='Farbe')), ('bold', wagtail.core.blocks.BooleanBlock(help_text='Für eine große und fette Überschrift', label='Fett', required=False))))), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow', label='Absatz')), ('image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(label='Bild')), ('caption', wagtail.core.blocks.CharBlock(label='Bildunterschrift', required=False)), ('full_width', wagtail.core.blocks.BooleanBlock(help_text='Soll das Bild auf voller Breite des Bildschirms angezeigt werden?', label='volle Breite', required=False))))), ('embedded_video', wagtail.core.blocks.StructBlock((('embed', wagtail.embeds.blocks.EmbedBlock('Video-URL', help_text='URL von z.B. Youtube oder Vimeo hier reinkopieren')), ('caption', wagtail.core.blocks.CharBlock(label='Bildunterschrift', required=False))))), ('button', wagtail.core.blocks.StructBlock((('text', wagtail.core.blocks.CharBlock(label='Text')), ('link', wagtail.core.blocks.URLBlock(label='Link')), ('color', wagtail.core.blocks.ChoiceBlock(choices=[('brown', 'Braun'), ('green', 'Grün'), ('red', 'Rot'), ('blue', 'Blau'), ('orange', 'Orange')], default='green', label='Farbe'))))), ('attachment', core.blocks.Attachment()), ('sticker', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(label='Text')), ('color', wagtail.core.blocks.ChoiceBlock(choices=[('brown', 'Braun'), ('green', 'Grün'), ('red', 'Rot'), ('blue', 'Blau'), ('orange', 'Orange')], default='green', label='Farbe')), ('link', wagtail.core.blocks.URLBlock(label='Link')))))), blank=True, verbose_name='Text'),
        ),
    ]
