# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20160911_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='personpage',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Telefonnummer'),
        ),
        migrations.AddField(
            model_name='personpage',
            name='role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rolle'),
        ),
    ]
