# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20160913_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personpage',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
    ]
