# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20161202_1828'),
        ('contact', '0009_auto_20161201_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactindex',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Header-Bild'),
        ),
        migrations.AddField(
            model_name='contactindex',
            name='heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Überschrift'),
        ),
    ]
