# Generated by Django 2.2.14 on 2020-09-08 10:14

import contact.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0023_contactpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "contact_block",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(label="Überschrift"),
                                ),
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        label="Text", required=False
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Bild", required=False
                                    ),
                                ),
                                (
                                    "telephone",
                                    wagtail.core.blocks.CharBlock(
                                        label="Telefon-Nummer", required=False
                                    ),
                                ),
                                (
                                    "telephone_hours",
                                    wagtail.core.blocks.CharBlock(
                                        label="Telefon-Nummer Öffnungszeiten",
                                        required=False,
                                    ),
                                ),
                                (
                                    "email",
                                    wagtail.core.blocks.EmailBlock(
                                        label="E-Mail-Adresse", required=False
                                    ),
                                ),
                                (
                                    "address",
                                    wagtail.core.blocks.RichTextBlock(
                                        lalbe="Adresse", required=False
                                    ),
                                ),
                                (
                                    "address_google",
                                    wagtail.core.blocks.URLBlock(
                                        label="Adresse bei Google", required=False
                                    ),
                                ),
                                (
                                    "address_osm",
                                    wagtail.core.blocks.URLBlock(
                                        label="Adresse bei OpenStreetMaps",
                                        required=False,
                                    ),
                                ),
                                (
                                    "address_directions",
                                    wagtail.core.blocks.URLBlock(
                                        label="Adresse: Link zu Wegbeschreibung",
                                        required=False,
                                    ),
                                ),
                                (
                                    "link_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Link-Text", required=False
                                    ),
                                ),
                                (
                                    "link_url",
                                    wagtail.core.blocks.URLBlock(
                                        label="Link-URL", required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="Inhalt",
            ),
        ),
    ]
