# Generated by Django 2.2.17 on 2020-12-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailinventory', '0001_initial'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contact', '0026_remove_contactpage_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officepage',
            name='basepage_ptr',
        ),
        migrations.RemoveField(
            model_name='officepage',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='basepage_ptr',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='office',
        ),
        migrations.RemoveField(
            model_name='personpage',
            name='photo',
        ),
        migrations.DeleteModel(
            name='ContactIndex',
        ),
        migrations.DeleteModel(
            name='OfficePage',
        ),
        migrations.DeleteModel(
            name='PersonPage',
        ),
    ]
