# Generated by Django 2.2.14 on 2020-07-08 15:06

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wimmelbilder', '0002_auto_20200708_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='WimmelbildPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Y-Position')),
                ('lng', models.FloatField(verbose_name='X-Position')),
                ('tooltip', models.CharField(blank=True, max_length=255, verbose_name='Tooltip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WimmelbildPointWimmelbildPage',
            fields=[
                ('wimmelbildpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wimmelbilder.WimmelbildPoint')),
                ('setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='wimmelbilder.WimmelbildPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wimmelbilder.wimmelbildpoint',),
        ),
    ]
