# Generated by Django 2.2.14 on 2020-07-08 15:35

import core.blocks
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wimmelbilder', '0003_wimmelbildpoint_wimmelbildpointwimmelbildpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wimmelbildpoint',
            name='content',
            field=wagtail.core.fields.StreamField([('paragraph', core.blocks.ParagraphBlock(features=['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Bild')), ('caption', wagtail.core.blocks.CharBlock(label='Bildunterschrift', required=False)), ('size', wagtail.core.blocks.ChoiceBlock(choices=[('text-width', 'Text-Breite'), ('over-text-width', 'Über-Text-Breite')]))])), ('video_link', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text='URL zu dem Video, auf das verlinkt wird', label='URL', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Bild (schwarz wenn nichts angegeben)', required=False)), ('caption', wagtail.core.blocks.CharBlock(label='Bild-Unterschrift', required=False))]))], blank=True, null=True, verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='wimmelbildpoint',
            name='tooltip',
            field=models.CharField(blank=True, help_text='Wird bei Hover angezeigt.', max_length=255, verbose_name='Tooltip'),
        ),
    ]
