# Generated by Django 2.2.14 on 2020-07-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wimmelbilder', '0004_auto_20200708_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='wimmelbildpage',
            name='height',
            field=models.FloatField(blank=True, help_text='Höhe des Wimmelbilds in Pixeln', null=True, verbose_name='Höhe'),
        ),
        migrations.AddField(
            model_name='wimmelbildpage',
            name='width',
            field=models.FloatField(blank=True, help_text='Breite des Wimmelbilds in Pixeln', null=True, verbose_name='Breite'),
        ),
    ]
