# Generated by Django 2.2.14 on 2020-07-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wimmelbilder', '0005_auto_20200708_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wimmelbildpage',
            name='height',
            field=models.IntegerField(blank=True, help_text='Höhe des Wimmelbilds in Pixeln', null=True, verbose_name='Höhe'),
        ),
        migrations.AlterField(
            model_name='wimmelbildpage',
            name='width',
            field=models.IntegerField(blank=True, help_text='Breite des Wimmelbilds in Pixeln', null=True, verbose_name='Breite'),
        ),
        migrations.AlterField(
            model_name='wimmelbildpoint',
            name='lat',
            field=models.IntegerField(verbose_name='Y-Position'),
        ),
        migrations.AlterField(
            model_name='wimmelbildpoint',
            name='lng',
            field=models.IntegerField(verbose_name='X-Position'),
        ),
    ]
