# Generated by Django 2.2.14 on 2020-07-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wimmelbilder', '0007_wimmelbildpoint_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wimmelbildpoint',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='Am besten kleines (30x30px) transparentes PNG. Fragezeichen wenn leer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Icon'),
        ),
    ]
