# Generated by Django 2.2.14 on 2020-07-09 16:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_delete_banner'),
        ('wimmelbilder', '0009_auto_20200708_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('icon', models.ForeignKey(blank=True, help_text='Am besten kleines (30x30px) freigestelltes PNG mit Umrandung. Größer ist Größer. Fragezeichen wenn leer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Icon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='wimmelbildpoint',
            name='icon',
        ),
        migrations.AddField(
            model_name='wimmelbildpoint',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='wimmelbilder.PointGroup', verbose_name='Punkt-Gruppe'),
        ),
        migrations.CreateModel(
            name='PointGroupWimmelbildPage',
            fields=[
                ('pointgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wimmelbilder.PointGroup')),
                ('setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='wimmelbilder.WimmelbildPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wimmelbilder.pointgroup',),
        ),
    ]
