# Generated by Django 2.2.14 on 2020-07-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wimmelbilder', '0011_auto_20200709_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointgroupwimmelbildpage',
            old_name='setting',
            new_name='page',
        ),
        migrations.RenameField(
            model_name='wimmelbildpointwimmelbildpage',
            old_name='setting',
            new_name='page',
        ),
        migrations.RemoveField(
            model_name='wimmelbildpoint',
            name='group',
        ),
    ]
