# Generated by Django 2.2.14 on 2020-07-25 16:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wimmelbilder', '0012_auto_20200725_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointGroupWimmelbildPoint',
            fields=[
                ('pointgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wimmelbilder.PointGroup')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('point', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='wimmelbilder.WimmelbildPoint')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('wimmelbilder.pointgroup', models.Model),
        ),
    ]
