# Generated by Django 2.2.14 on 2020-07-25 16:31

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wimmelbilder', '0013_pointgroupwimmelbildpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='wimmelbildpoint',
            name='group',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='wimmelbilder.PointGroup'),
        ),
        migrations.DeleteModel(
            name='PointGroupWimmelbildPoint',
        ),
    ]
