# Generated by Django 2.2.14 on 2020-07-25 16:32

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wimmelbilder', '0014_auto_20200725_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wimmelbildpoint',
            name='group',
            field=modelcluster.fields.ParentalKey(blank=True, help_text='Wird ohne Gruppe nicht angezeigt. Auswählen geht bei neuen Gruppen erst nach Speichern', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='wimmelbilder.PointGroup', verbose_name='Gruppe'),
        ),
    ]
