# Generated by Django 2.2.14 on 2020-07-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wimmelbilder', '0015_auto_20200725_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wimmelbildpoint',
            name='group',
            field=models.CharField(blank=True, help_text='Exakter Name der Gruppe', max_length=255, null=True, verbose_name='Gruppe'),
        ),
    ]
