# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0033_auto_20160830_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BasePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basepage',),
        ),
    ]
