# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20161202_1515'),
        ('about', '0007_auto_20161201_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='intro_text',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Header-Bild'),
        ),
    ]
