# Generated by Django 2.2.17 on 2020-12-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailinventory', '0001_initial'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('about', '0021_auto_20201225_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
