# Generated by Django 2.2.14 on 2020-11-16 16:34

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gridcal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridcalendar',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Intro-Text'),
        ),
        migrations.AlterField(
            model_name='gridcalendar',
            name='show_placeholder_for_unpublished',
            field=models.BooleanField(default=False, help_text='Normalerweise werden unveröffentlichte Einträge gar nicht angezeigt', verbose_name='Zeige Platzhalter für unveröffentlichte Einträge'),
        ),
    ]
