# Generated by Django 2.2.17 on 2020-12-01 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20201129_1405'),
        ('gridcal', '0002_auto_20201116_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcalendar',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Bild, das den Artikel repräsentiert. Wird in Übersichten verwendet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.AttributedImage', verbose_name='Bild für Übersichten'),
        ),
    ]
