# Generated by Django 2.2.12 on 2020-06-04 22:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', wagtail.core.fields.StreamField([('submenu', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Leer lassen, um Titel der Seite zu benutzen', label='Titel', required=False)), ('submenu', wagtail.core.blocks.StreamBlock([('category', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Titel')), ('submenu', wagtail.core.blocks.StreamBlock([('internal_page', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Leer lassen, um Titel der Seite zu benutzen', label='Titel', required=False)), ('subtitle', wagtail.core.blocks.CharBlock(label='Untertitel', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Seite'))]))], label='Untermenü'))]))]))])), ('internal_page', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Leer lassen, um Titel der Seite zu benutzen', label='Titel', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Seite'))]))])),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Menü',
            },
        ),
    ]
